### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/modulesync#128]
Please release new gem version

**Comment by rnelson0** [comment]
@cdenneen We can release a new gem version once there's a PR with a changelog update. If you can help put that together we can review it and release.

**Comment by cdenneen** [comment]
@rnelson0 I would love to but currently the github_changelog_generator doesn't produce the format you guys are using.
If you could document the process to generate your particular format I would be happy to.

**Comment by rnelson0** [comment]
We are willing to convert formats, and there's no time like the present time to make the change!

**Comment by cdenneen** [comment]
@rnelson0 I haven't gone through to switch to using github_changelog_generator I just manually updated since it seems no one else has created a PR #134

**Comment by cdenneen** [comment]
Can this please be merged and released?

**Comment by ekohl** [comment]
Tagged and on rubygems now.
