### ISSUE TITLE
Can skip_broken still return a non-zero exit?

### ISSUE THREAD

**Issue by asedge** [voxpupuli/modulesync#132]
I would like to complete the entire run but have ModuleSync still report there was an error so I can take some action when it finishes. Could we find a way to support this behavior? Willing to file a PR.

**Comment by rnelson0** [comment]
@asedge I think if that functionality were its own setting so users could really skip brokens or throw a flag on brokens, like gcc's `-Werror` flag, we would happily take it.

**Comment by asedge** [comment]
@rnelson0 So do you see it being a new option like `--skip-broken-with-exitstatus` or do you see it being a separate option that must be used with `--skip-broken`?  Also do you have an opinion on what it should be called?  I'm not fond of the example I used above but am having difficulty thinking of something descriptive and short.

**Comment by rnelson0** [comment]
`msync ... --skip-broken --fail-on-warnings` might work. It could then be used with any other warning-level flags to produce failures. Other names might be `--strict_mode, --strict_failures`. I don't know if anyone else has thoughts on the flag name for this @danzilio @bastelfreak
