### ISSUE TITLE
Change project tagline (on GitHub) to reflect current feature set

### ISSUE THREAD

**Issue by bittner** [voxpupuli/modulesync#156]
The project tagline on GitHub currently reads:

> Synchronize common files between github module repositories.

This is somewhat not totally true anymore. The tool is not limited to use with GitHub and with Puppet modules. I propose to change the text to:

> Synchronize common files across your Git repositories.

Why?

While only GitHub PRs are supported, any Git repository will work fine for the rest of the provided functionality, and (configuration) files from any type of Git repository and project can by synced, not just Puppet modules.

**Comment by ekohl** [comment]
I don't have the permissions to do so, but :+1: from me. @bastelfreak do you have permissions?

**Comment by rnelson0** [comment]
Done. Thanks for pointing this out, @bittner!
