### ISSUE TITLE
"Using ModuleSync is now deprecated" according to PuppetLabs (?)

### ISSUE THREAD

**Issue by bittner** [voxpupuli/modulesync#160]
According to the PuppetLabs [modulesync_config repository README](https://github.com/puppetlabs/modulesync_configs#modulesync-configs), _"Using ModuleSync is now deprecated."_

Can someone clarify what this means in our context?

Will this repository continue to exist independently of PuppetLabs' decision to stop using ModuleSync? (The feature set is of great value even outside of the area of Puppet, isn't it?)

**Comment by alexjfisher** [comment]
Yes, voxpupuli are still using and maintaining modulesync.
It’s only Puppet inc that have stopped using it to manage their modules.

**Comment by glennsarti** [comment]
@bittner Sorry...I should explain myself better.....The USE of modsync on the Puppetlabs modules is deprecated in favour of using PDK.  Modsync itself is not deprecated.

Note the warning is on the modsync_configs (which contains Puppetlabs modsync configuration) repo, not the modsync repo.

**Comment by glennsarti** [comment]
Sorry for the confusion there.  Would you prefer I clarify that in the modsync_configs repo?

**Comment by bittner** [comment]
> Sorry for the confusion there. Would you prefer I clarify that in the modsync_configs repo?

Yes! That is what I care for. - Thank you!

**Comment by bittner** [comment]
The "deprecation notice" has been fixed via https://github.com/puppetlabs/modulesync_configs/pull/209, lately.
