### ISSUE TITLE
Please adjust the dependency to puppet-blacksmith's current version

### ISSUE THREAD

**Issue by dbro86** [voxpupuli/modulesync#196]
Dear developers,
Is it possible to increase the dependency to puppet-blacksmith's current version 6.0.0?

Kind regards
Brody

**Comment by ekohl** [comment]
This repo is the modulesync software itself rather than the config Voxpupuli uses. Perhaps you're looking for https://github.com/voxpupuli/modulesync_config.

**Comment by bastelfreak** [comment]
oh, we haven't updated the dependency in years :( PR is https://github.com/voxpupuli/modulesync/pull/197
