### ISSUE TITLE
Remove file namespaces from configuration

### ISSUE THREAD

**Issue by domcleal** [voxpupuli/modulesync#27]
While in the process of updating our modules to move from a Rakefile config to .puppet-lint.rc, I realised that the config keys are underneath the filename in .sync.yml rather than being accessible in all templates.

The downside of this is that they're only accessible in the template for that one file, so if you're trying to move things from one file to another, you can no longer access the config entries.  Instead you need to either update .sync.yml and duplicate the data for the second file, or update it in the local modules/ checkouts etc.

Maybe the file namespace should be removed and have config keys more global?  It might be useful to reuse configuration in multiple files too.

**Comment by DavidS** [comment]
That might be fixed in #36, where I've added a :global key.

**Comment by bittner** [comment]
Can we close this issue?
