### ISSUE TITLE
make a fresh release

### ISSUE THREAD

**Issue by igalic** [voxpupuli/modulesync#75]
I think we've had some changes in that deserve a fresh 1.x release

**Comment by jlambert121** [comment]
Personally I'm looking for the custom namespace stuff - it would be great to have it tagged in a release.

**Comment by igalic** [comment]
@danzilio ping

**Comment by danzilio** [comment]
hiiiii @igalic! sorry i've been MIA lately. busy few weeks. i'll try and prep a release this weekend

**Comment by igalic** [comment]
oh right, you're MOVING HOUSE OMG SORRY
maybe someone else can help!

**Comment by jrwesolo** [comment]
I'd love to see this too!

**Comment by domcleal** [comment]
modulesync 0.7.2 (after some release bugs with .0, .1) is now available on rubygems.org.
