### ISSUE TITLE
Honour git repo default branch

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/modulesync#76]
`msync update -b modulesync --noop -f my_module` clones `my_module` and creates a new `modulesync` branch based off of `master`.  I'm using gitflow, and the default branch is configured as `develop` not `master`.  I would expect modulesync to honour the module's default branch and create the modulesync branch off of develop instead.

**Comment by igalic** [comment]
yes please

**Comment by ekohl** [comment]
Fixed in https://github.com/voxpupuli/modulesync/pull/142
