### ISSUE TITLE
create a script/extension to automatically create PRs

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync#80]
I think the title describes it very good. also @bbriggs said he is interested in implementing this

**Comment by bbriggs** [comment]
Unless anyone has objections, I plan to just extend the existing gem in Ruby as opposed to adding a new script. The feature will be triggered with a command line switch.

**Comment by bastelfreak** [comment]
@danzilio do you have any suggestions here?

**Comment by danzilio** [comment]
Sounds good to me. Honestly, I'd like to see a plugin system here (for example, it would be nice to support submitting PRs for GitLab and Stash as well) but that's a much bigger task. Let's see what this looks like and go from there.

**Comment by bbriggs** [comment]
So maybe a modulesync-github-pr gem, then?

**Comment by bbriggs** [comment]
And then have the modulesync-*-pr gems provide a common API to modulesync so it can choose the appropriate gem/plugin to call when --auto-pr is enabled?

**Comment by danzilio** [comment]
@bbriggs Exactly! I'd loooove to see that. But, right now, the API in modulesync isn't particularly robust. It would definitely be an undertaking. Although, maybe this is a good place to start...

**Comment by rnelson0** [comment]
modulesync-pr-* would probably be better for sorting, tab completion, etc,

>

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by bbriggs** [comment]
I guess now I get to write my first gem. Yay Ruby!

**Comment by sean797** [comment]
@bbriggs did you ever make a start on this ?

**Comment by bbriggs** [comment]
:(

**Comment by bbriggs** [comment]
In my heart I really want to but realistically I don't think I'll be able to get to this.

**Comment by timhughes** [comment]
not the most elegant code but here is what I use for gitlab  https://gist.github.com/timhughes/80928f02baf7ee5c52180b16f0a2ba0b

**Comment by ekohl** [comment]
Personally I use the following:

```bash
rm -rf modules
bundle exec msync update --noop
# Ensure all modules are good to go - hopefully nothing was changed in files but not .sync.yml
MESSAGE="..."
for mod in modules/* ; do
    echo "Handling $mod"
    git commit -a -m "$MESSAGE" && git push $(whoami) HEAD -u && hub pull-request -m "$MESSAGE"
done
```

Personally I like the control over msync doing the commits but in general it's clear. https://hub.github.com/ is a great tool and I'd be a lot less efficient at using github if I had to use the UI to do PRs.

**Comment by bittner** [comment]
Any hope we'll see a GitLab MR feature in modulesync anytime soon?

**Comment by bittner** [comment]
The GitLab integration module of choice would probably be https://narkoz.github.io/gitlab/.

**Comment by bittner** [comment]
Just a heads-up to make interested parties understand how we at @vshn use ModuleSync.

- https://vshn.ch/en/blog/how-we-manage-100-web-application-firewalls/

Thanks everyone here for this great tool that proves to be so useful! :100: :rocket: :bowing_man: :bowing_woman: 

BTW, can we now close this ticket? Creating GitHub PRs and GitLab MRs is now possible.

**Comment by bastelfreak** [comment]
thanks for the reminder. I agree that we should close this issue
