### ISSUE TITLE
Specify ruby requirements in gemspec

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/modulesync#82]
Per https://github.com/voxpupuli/modulesync/blob/master/.travis.yml#L7 it looks like this requires ruby 1.9.3. Whatever the required version is, explicitly state this in the gemspec, e.g. `s.required_ruby_version = '>= 1.9.3'`

**Comment by bastelfreak** [comment]
Hi @rnelson0, we just did https://github.com/voxpupuli/modulesync/pull/109 which fixes this. let me know if you need a release with this fix.

**Comment by rnelson0** [comment]
I think it can wait till release 0.8.0.
