### ISSUE TITLE
Language sensitive GIT handling

### ISSUE THREAD

**Issue by lazyfrosch** [voxpupuli/modulesync#85]
The line here is language specific, and would break on non-english.

``` ruby
if git_error.message.include? 'nothing to commit, working directory clean'
```

https://github.com/voxpupuli/modulesync/blob/master/lib/modulesync/git.rb#L129

Only help for now is:

```
LANG=C msync update ...
```

**Comment by ekohl** [comment]
Looks like this exact message was changed but is still parsing the error message: https://github.com/voxpupuli/modulesync/blob/5b9c908887aa5e5489bddf22284909617d3c20eb/lib/modulesync/git.rb#L135
